# Generated by Django 6.0.1 on 2026-01-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('assistant_project_manager', 'Assistant Project Manager'), ('circle_manager', 'Circle Manager'), ('team_leader', 'Team Leader'), ('back_office_head', 'Back Office Head'), ('back_office', 'Back Office'), ('accountant', 'Accountant'), ('flying_officer_sspl', 'Flying Officer SSPL'), ('revenue_officer', 'Revenue Officer'), ('zone_commissioner', 'Zone Commissioner'), ('revenue_inspector', 'Revenue Inspector'), ('surveyor', 'Surveyor'), ('tax_collector', 'Tax Collector'), ('tele_caller', 'Tele Caller'), ('mis', 'MIS'), ('counter', 'Counter'), ('commissioner', 'Commissioner'), ('oswal', 'Oswal'), ('ulb_admin', 'ULB Admin'), ('qr_installer', 'QR Installer'), ('dc_revenue_first', 'DC Revenue First'), ('ro_revenue_first', 'RO Revenue First'), ('testt', 'TESTT')], default='back_office', max_length=30, verbose_name='Role'),
        ),
    ]
