# Generated by Django 6.0.1 on 2026-01-31 08:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('service_no', models.CharField(max_length=50, unique=True, verbose_name='Service Number')),
                ('unique_key', models.CharField(max_length=100, unique=True, verbose_name='Unique Key')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('form_completed', 'Form Completed'), ('geotagged', 'Geotagged'), ('completed', 'Completed'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('tax_paid', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('partial', 'Partial')], max_length=10)),
                ('one_time_paid', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('multi_storage_complex', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('is_ex_party', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('surveyor_notes', models.TextField(blank=True, verbose_name='Surveyor Notes')),
                ('verification_notes', models.TextField(blank=True, verbose_name='Verification Notes')),
                ('surveyor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Survey',
                'verbose_name_plural': 'Surveys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100, verbose_name='Owner Name')),
                ('guardian_name', models.CharField(max_length=100, verbose_name='Guardian Name')),
                ('age', models.PositiveIntegerField(verbose_name='Age')),
                ('mobile_no', models.CharField(max_length=15, verbose_name='Mobile Number')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('profession', models.CharField(choices=[('business', 'Business'), ('service', 'Service'), ('agriculture', 'Agriculture'), ('retired', 'Retired'), ('housewife', 'Housewife'), ('student', 'Student'), ('unemployed', 'Unemployed'), ('other', 'Other')], max_length=20)),
                ('relation', models.CharField(choices=[('self', 'Self'), ('father', 'Father'), ('mother', 'Mother'), ('spouse', 'Spouse'), ('son', 'Son'), ('daughter', 'Daughter'), ('brother', 'Brother'), ('sister', 'Sister'), ('other', 'Other')], max_length=20)),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='survey_process.survey')),
            ],
            options={
                'verbose_name': 'Property Owner',
                'verbose_name_plural': 'Property Owners',
            },
        ),
        migrations.CreateModel(
            name='PropertyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(choices=[('area1', 'Area 1'), ('area2', 'Area 2'), ('area3', 'Area 3'), ('area4', 'Area 4')], max_length=20, verbose_name='Area Name')),
                ('ward_no', models.CharField(choices=[('ward1', 'Ward 1'), ('ward2', 'Ward 2'), ('ward3', 'Ward 3'), ('ward4', 'Ward 4')], max_length=20, verbose_name='Ward Number')),
                ('road_type', models.CharField(choices=[('paved', 'Paved Road'), ('unpaved', 'Unpaved Road'), ('concrete', 'Concrete Road'), ('gravel', 'Gravel Road')], max_length=20, verbose_name='Road Type')),
                ('ownership_type', models.CharField(choices=[('freehold', 'Freehold'), ('leasehold', 'Leasehold'), ('rental', 'Rental'), ('government', 'Government')], max_length=20, verbose_name='Ownership Type')),
                ('use_of_property', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('mixed', 'Mixed Use'), ('institutional', 'Institutional')], max_length=20, verbose_name='Use of Property')),
                ('plot_area_sq_yd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Plot Area (Sq Yd)')),
                ('plinth_area_sq_yd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Plinth Area (Sq Yd)')),
                ('vacant_area_sq_yd', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Vacant Area (Sq Yd)')),
                ('no_of_floors', models.PositiveIntegerField(verbose_name='Number of Floors')),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='survey_process.survey')),
            ],
            options={
                'verbose_name': 'Property Details',
                'verbose_name_plural': 'Property Details',
            },
        ),
        migrations.CreateModel(
            name='PropertyAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking', models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available'), ('partial', 'Partial')], default='not_available', max_length=15)),
                ('street_light', models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available'), ('partial', 'Partial')], default='not_available', max_length=15)),
                ('sewer_line', models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available'), ('partial', 'Partial')], default='not_available', max_length=15)),
                ('electricity_connection', models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available'), ('partial', 'Partial')], default='not_available', max_length=15)),
                ('private_toilet', models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available'), ('partial', 'Partial')], default='not_available', max_length=15)),
                ('sewer_connection', models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available'), ('partial', 'Partial')], default='not_available', max_length=15)),
                ('septic_tank', models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available'), ('partial', 'Partial')], default='not_available', max_length=15)),
                ('open_toilet', models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available'), ('partial', 'Partial')], default='not_available', max_length=15)),
                ('piped_water_connection', models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available'), ('partial', 'Partial')], default='not_available', max_length=15)),
                ('fire_fighting_system', models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available'), ('partial', 'Partial')], default='not_available', max_length=15)),
                ('boring', models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available'), ('partial', 'Partial')], default='not_available', max_length=15)),
                ('mobile_tower', models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available'), ('partial', 'Partial')], default='not_available', max_length=15)),
                ('advertising_hoarding', models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available'), ('partial', 'Partial')], default='not_available', max_length=15)),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='survey_process.survey')),
            ],
            options={
                'verbose_name': 'Property Amenities',
                'verbose_name_plural': 'Property Amenities',
            },
        ),
        migrations.CreateModel(
            name='PropertyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.CharField(max_length=50, verbose_name='House Number')),
                ('mohalla_colony_name', models.CharField(max_length=100, verbose_name='Mohalla/Colony Name')),
                ('building_name', models.CharField(blank=True, max_length=100, verbose_name='Building Name')),
                ('road_name', models.CharField(max_length=100, verbose_name='Road Name')),
                ('sector', models.CharField(max_length=50, verbose_name='Sector')),
                ('mobile_no', models.CharField(max_length=15, verbose_name='Mobile Number')),
                ('phone_no', models.CharField(blank=True, max_length=15, verbose_name='Phone Number')),
                ('email_id', models.EmailField(blank=True, max_length=254, verbose_name='Email ID')),
                ('landmark', models.CharField(blank=True, max_length=100, verbose_name='Landmark')),
                ('pincode', models.CharField(max_length=10, verbose_name='Pincode')),
                ('permanent_address', models.TextField(verbose_name='Permanent Address')),
                ('same_as_permanent', models.BooleanField(default=False, verbose_name='Same as Permanent Address')),
                ('communication_address', models.TextField(blank=True, verbose_name='Communication Address')),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='survey_process.survey')),
            ],
            options={
                'verbose_name': 'Property Address',
                'verbose_name_plural': 'Property Addresses',
            },
        ),
        migrations.CreateModel(
            name='SurveyGeotagging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Longitude')),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='GPS Accuracy (meters)')),
                ('front_photo', models.ImageField(upload_to='survey_photos/front/', verbose_name='Front Photo')),
                ('side_photo_1', models.ImageField(upload_to='survey_photos/side/', verbose_name='Side Photo 1')),
                ('side_photo_2', models.ImageField(upload_to='survey_photos/side/', verbose_name='Side Photo 2')),
                ('geotagged_at', models.DateTimeField(auto_now_add=True)),
                ('device_info', models.CharField(blank=True, max_length=200, verbose_name='Device Information')),
                ('geotagged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geotagging', to='survey_process.survey')),
            ],
            options={
                'verbose_name': 'Survey Geotagging',
                'verbose_name_plural': 'Survey Geotagging',
            },
        ),
        migrations.CreateModel(
            name='SurveyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Survey Created'), ('form_filled', 'Form Filled'), ('geotagged', 'Geotagged'), ('completed', 'Completed'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('updated', 'Updated')], max_length=20)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='survey_process.survey')),
            ],
            options={
                'verbose_name': 'Survey History',
                'verbose_name_plural': 'Survey History',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='FloorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_name', models.CharField(choices=[('ground', 'Ground Floor'), ('first', 'First Floor'), ('second', 'Second Floor'), ('third', 'Third Floor'), ('fourth', 'Fourth Floor'), ('basement', 'Basement')], max_length=20, verbose_name='Floor Name')),
                ('use_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('office', 'Office'), ('shop', 'Shop'), ('godown', 'Godown'), ('parking', 'Parking')], max_length=20, verbose_name='Use Type')),
                ('usage_type', models.CharField(choices=[('self_occupied', 'Self Occupied'), ('rented', 'Rented'), ('vacant', 'Vacant'), ('under_construction', 'Under Construction')], max_length=20, verbose_name='Usage Type')),
                ('from_year', models.PositiveIntegerField(verbose_name='From Year')),
                ('upto_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Upto Year')),
                ('built_up_area_sq_ft', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Built Up Area (Sq Ft)')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='survey_process.survey')),
            ],
            options={
                'verbose_name': 'Floor Details',
                'verbose_name_plural': 'Floor Details',
                'unique_together': {('survey', 'floor_name')},
            },
        ),
    ]
