# Generated by Django 6.0.1 on 2026-02-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_process', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='survey_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Survey Number'),
        ),
    ]
