"""
Django settings for Rajasthan_Municipal project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!rgk8rli4z(xg4gvpsbxugw^ger+_1n*d)*cat3$y)xe0a3x2m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'survey_process',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Rajasthan_Municipal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Rajasthan_Municipal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# Custom User Model
AUTH_USER_MODEL = 'users.CustomUser'

# Media files (for image uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Login/Logout URLs
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =============================================================================
# SMS SERVICE CONFIGURATION
# =============================================================================

# Default SMS provider: 'free', 'fast2sms', 'msg91', 'twilio', or 'textlocal'
DEFAULT_SMS_PROVIDER = 'fast2sms'
FAST2SMS_API_KEY = 's0y8ktAJjTiCX1QxnvVlEpm7uP43Wdq9HeawKzcMZ5R6YNr2USk70Fulzw4h8pImsx2yRBvEY9qVA1Cb'

# MSG91 Configuration (Recommended for India)
# Sign up at: https://msg91.com/
MSG91_AUTH_KEY = 'your_msg91_auth_key_here'  # Replace with your actual key
MSG91_SENDER_ID = 'OTPSMS'
MSG91_ROUTE = '4'  # Transactional route

# Twilio Configuration (International)
# Sign up at: https://www.twilio.com/
TWILIO_ACCOUNT_SID = 'your_twilio_account_sid_here'  # Replace with your actual SID
TWILIO_AUTH_TOKEN = 'your_twilio_auth_token_here'    # Replace with your actual token
TWILIO_PHONE_NUMBER = '+1234567890'                  # Replace with your Twilio number

# TextLocal Configuration (India)
# Sign up at: https://www.textlocal.in/
TEXTLOCAL_API_KEY = 'your_textlocal_api_key_here'    # Replace with your actual key
TEXTLOCAL_SENDER = 'TXTLCL'

# Logging configuration for SMS services
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'sms.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'users.sms_services': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
# Fast2SMS Configuration (Free tier available)
# Sign up at: https://www.fast2sms.com/
FAST2SMS_API_KEY = 'your_fast2sms_api_key_here'  # Replace with your actual key
FAST2SMS_SENDER_ID = 'FSTSMS'

# Way2SMS Configuration (Free service)
# Sign up at: https://www.way2sms.com/
WAY2SMS_API_KEY = 'your_way2sms_api_key_here'    # Replace with your actual key
WAY2SMS_SECRET = 'your_way2sms_secret_here'      # Replace with your actual secret

# Free SMS Service Configuration (for testing)
SMS_TEST_MODE = True
SMS_TEST_NUMBERS = ['+919876543210', '+919123456789']  # Add your test numbers here